include ../config

SUBDIRS += bdb blit conio directory-list ingle lineedit lisp log posix simpleio text tunix zp

ifeq ($(TARGET), vic20)
SUBDIRS += gfx gui keyboard term term-test text ultifs ultimem
endif

include ../Makefile.subdir
