LIBRARY = liblisp.a
SOURCES = \
	builtin.c \
	error.c \
	eval.c \
	gc.c \
	global-pointers.c \
	heap.c \
	image.c \
	io.c \
	list.c \
	print.c \
	repl.c \
	slow.c \
	read.c

include ../../mk/Makefile.build
