LIBRARY=libgui.a
SOURCES= \
    box.c \
    button.c \
    error.c \
    event.c \
    frame.c \
    inputline.c \
    layout-ops.c \
    list.c \
    table.c \
    message.c \
    obj.c \
    window.c

include ../../Makefile.build
