LIBRARY=libultimem.a
ASMSOURCES= \
    burn.asm \
    bank-offset.asm \
    c-copy.asm \
    commands.asm \
    copy.asm \
    detect.asm \
    erase.asm \
    readwrite.asm \
    unhide.asm

include ../../Makefile.build
