#include <string.h>
#include <stdio.h>

#include "token-table.c"

int
main (int argc, char *argv[])
{
    printf ("// Generated by Small-C's mktok.\n");
    for (int i = 0; tokens[i].name; i++)
        printf ("#define TOK%s %d\n",
                tokens[i].name, i + 1);
}
