;
; File generated by cc65 v 2.15 - Git f1d7679
;
	.fopt		compiler,"cc65 v 2.15 - Git f1d7679"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_printf
	.export		_main

.segment	"RODATA"

L0003:
	.byte	$C8,$C5,$CC,$CC,$CF,$21,$0D,$00

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (__near__ __near__ unsigned char * *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	txa
	jmp     incsp4

.endproc

