SRC := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/..

-include $(SRC)/config

COMMODORE_TARGETS = c128 c16 c64 pet plus4 vic20
CC65_TARGETS 	  = $(COMMODORE_TARGETS)
GCC_TARGETS 	  = unix
VALID_TARGETS     = $(CC65_TARGETS) $(GCC_TARGETS)

ifneq (,$(filter $(TARGET), $(CC65_TARGETS)))
TARGETCC=cc65
endif
ifneq (,$(filter $(TARGET), $(GCC_TARGETS)))
TARGETCC=gcc
endif

TUNIX_LIB ?= $(SRC)/lib

PROGRAM_PLAIN  = $(PROGRAM).prg

EXOMIZER ?= $(SRC)/contrib/exomizer-3.0.2/src/exomizer
EXOMIZER_FLAGS ?= -B -n

include $(SRC)/mk/Makefile.config.$(TARGETCC)

ifdef NAIVE
CFLAGS += -DNAIVE
endif

ifdef NDEBUG
CFLAGS += -DNDEBUG
endif

ifdef NO_DEBUGGER
CFLAGS += -DNO_DEBUGGER
endif

ifdef NO_ONERROR
CFLAGS += -DNO_ONERROR
endif

ifeq ($(TARGET), c128)
CFLAGS += -DTARGET_C128
endif
ifeq ($(TARGET), c16)
CFLAGS += -DTARGET_C16
endif
ifeq ($(TARGET), c64)
CFLAGS += -DTARGET_C64
endif
ifeq ($(TARGET), pet)
CFLAGS += -DTARGET_PET
endif
ifeq ($(TARGET), plus4)
CFLAGS += -DTARGET_PLUS4
endif
ifeq ($(TARGET), unix)
CFLAGS += -DTARGET_UNIX
endif
ifeq ($(TARGET), vic20)
CFLAGS += -DTARGET_VIC20
endif
