SRC := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/..

-include $(SRC)/config

COMMODORE_TARGETS = c128 c64 pet plus4 vic20
CC65_TARGETS 	  = $(COMMODORE_TARGETS)
GCC_TARGETS 	  = unix
VALID_TARGETS     = $(CC65_TARGETS) $(GCC_TARGETS)

ifneq (,$(filter $(TARGET), $(CC65_TARGETS)))
TARGETCC=cc65
endif
ifneq (,$(filter $(TARGET), $(GCC_TARGETS)))
TARGETCC=gcc
endif

TUNIX_LIB ?= $(SRC)/lib

PROGRAM_PLAIN  = $(PROGRAM).prg

EXOMIZER ?= $(SRC)/contrib/exomizer-3.0.2/src/exomizer
EXOMIZER_FLAGS ?= -B -n

include $(SRC)/mk/Makefile.config.$(TARGETCC)
