THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
SRC := $(THIS_DIR)/..

-include $(SRC)/config
ifndef TARGET
TARGET=unix
endif

include $(SRC)/mk/Makefile.targets

ifneq (,$(filter $(TARGET), $(CC65_TARGETS)))
TARGETCC=cc65
endif
ifneq (,$(filter $(TARGET), $(GCC_TARGETS)))
TARGETCC=gcc
endif
ifneq (,$(filter $(TARGET), $(ZCC_TARGETS)))
TARGETCC=zcc
endif

TUNIX_INCLUDE ?= $(SRC)/include
TUNIX_LIB     ?= $(SRC)/lib

PROGRAM_PLAIN  = $(PROGRAM).prg

EXOMIZER ?= $(SRC)/contrib/exomizer-3.0.2/src/exomizer
EXOMIZER_FLAGS ?= -B -n

include $(SRC)/mk/Makefile.config.$(TARGETCC)

ifdef NDEBUG
CFLAGS += -DNDEBUG
endif

ifdef TEST
CFLAGS += -DTEST
endif

ifeq ($(TARGET), c128)
CFLAGS += -DTARGET_C128
endif
ifeq ($(TARGET), c16)
CFLAGS += -DTARGET_C16
endif
ifeq ($(TARGET), c64)
CFLAGS += -DTARGET_C64
endif
ifeq ($(TARGET), cpm)
CFLAGS += -DTARGET_CPM
endif
ifeq ($(TARGET), pet)
CFLAGS += -DTARGET_PET
endif
ifeq ($(TARGET), plus4)
CFLAGS += -DTARGET_PLUS4
endif
ifeq ($(TARGET), sim6502)
CFLAGS += -DTARGET_SIM6502
endif
ifeq ($(TARGET), unix)
CFLAGS += -DTARGET_UNIX
endif
ifeq ($(TARGET), vic20)
CFLAGS += -DTARGET_VIC20
endif
ifeq ($(TARGET), zx)
CFLAGS += -DTARGET_ZX
endif
