#include <stdio.h>

#include "ir-table.c"

int
main (int argc, char *argv[])
{
    int i;

    printf ("// Generated by Small-C's mkir.\n");

    for (i = 0; codes[i].name; i++)
        printf ("#define IR_%s %d\n",
                codes[i].name, i + 1);
}
