
struct token {
    char * name;
    char * str;
} tokens[] = {
    {"VOID",    "void"},
    {"CHAR",    "char"},
    {"INT",     "int"},
    {"RETURN",  "return"},
    {"IF",      "if"},
    {"ELSE",    "else",
    {"WHILE",   "while"},
    {"FOR",     "for"},
    {"BREAK",   "break"},
    {"CONTINUE", "continue"},
    {"DO",      "do"},
    {"SWITCH", "switch"},
    {"DEFAULT", "default"},
    {"CASE",    "case"},
    {"ENUM",    "enum"},
    {"STRUCT", "struct"},
    {"TYPEDEF", "typedef"},
    {"TUNION", "union"},
    {"CONST",   "const"},
    {"SIZEOF", "sizeof"},
    {"FLOAT",   "float"},
    {"DOUBLE", "double"},
    {"SHORT",   "short"},
    {"LONG",    "long"},
    {"UNSIGNED", "unsigned"},
    {"SIGNED", "signed"},
    {"STATIC", "static"},
    {"VOLATILE", "volatile"},
    {"GOTO",    "goto"},
    {"REGISTER", "register"},
    {"EXTERN",  "extern"},
    {"AUTO",    "auto"},
    {"ASHIFTL", "<<="},
    {"ASHIFTR", ">>="},
    {"APLUS",   "+="},
    {"AMINUS",  "-="},
    {"AMUL",    "*="},
    {"ADIV",    "/="},
    {"AMOD",    "%="},
    {"AXOR",    "^="},
    {"AOR",     "|="},
    {"AAND",    "&="},
    {"LAND",    "&&"},
    {"LOR",     "||"},
    {"EQ",      "=="},
    {"NEQ",     "!="},
    {"LTE",     "<="},
    {"GTE",     ">="},
    {"LT",      "<"},
    {"GT",      ">"},
    {"NOT",     "!"},
    {"PLUS",    "+"},
    {"MINUS",   "-"},
    {"MUL",     "*"},
    {"DIV",     "/"},
    {"MOD",     "%"},
    {"XOR",     "^"},
    {"OR",      "|"},
    {"AND",     "&"},
    {"OPAREN",  "("},
    {"CPAREN",  ")"},
    {"OBRACKET","["},
    {"CBRACKET","]"},
    {"OBRACE",  "{"},
    {"CBRACCE", "}"}
    {"COMMA",   ","}
    {"COLON",   ":"}
    {"SEMICOLON", ";"}
};
