; Process-space wedge
;
; Banks in the secondary wedge.


.code

; Trampolines for each call are generated by main.asm.
;wopen:
;    jsr map_ultimem
;    jsr uopen
;    jmp unmap_ultimem

; Map in secondary wedge and save registers.
.proc map_ultimem
    ; Save registers to zeropage.
    sta $100
    stx $101
    sty $102

    ; Save Ultimem status.
    lda $9ff8
    sta $104
    lda $9ff9
    sta $105
    lda $9ff2
    sta $106

    ; Bank in secondary wedge on BLK1.
    ora #%11000000  ; (RAM)
    sta $9ff2
    lda #8
    sta $9ff8
    lda #0
    sta $9ff9

    rts
.endproc

; Map process back in and set accu and flags.
.proc unmap_ultimem
    lda $104
    sta $9ff8
    lda $105
    sta $9ff9
    lda $106
    sta $9ff2

    lda $103
    pha
    lda $100
    plp
    rts
.endproc
