; Process-space wedge
;
; To be as small as it can.  Banks in the UltiFS bank
; and calls functions of the secondary wedge, written
; in C.

.code

; Trampolines for each call are generated by main.asm.
;wopen:
;    jsr map_ultimem
;    jsr uopen
;    jmp unmap_ultimem

; Map in secondary wedge and save registers.
.proc map_ultimem
    ; Save registers to zeropage.
    sta $100
    stx $101
    sty $102

    ; Save Ultimem status.
    lda $9ff2
    sta $103
    lda $9ff8
    sta $104
    lda $9ff9
    sta $105

    ; Map in UltiFS wedge.
    lda #8
    sta $9ff8
    lda #0
    sta $9ff9

    rts
.endproc

; Map process back in and set accu and flags.
.proc unmap_ultimem
    ; Restore Ultimem status.
    lda $103
    sta $9ff2
    lda $104
    sta $9ff8
    lda $105
    sta $9ff9

    lda $106
    pha
    lda $107
    plp
    rts
.endproc
