PROGRAM=lisp
SOURCES= \
	main.c
LIBRARIES= \
    $(TUNIX_LIB)/term/libterm.a \
    $(TUNIX_LIB)/gfx/libgfx.a \
    $(TUNIX_LIB)/blit/libblit.a \
    $(TUNIX_LIB)/ingle/libingle.a \
    $(TUNIX_LIB)/ultimem/libultimem.a

include ../Makefile.native
