# List of subdirectories containing their own Makefiles
SUBDIRS ?= $(shell find . -mindepth 1 -maxdepth 1 -type d)

# Default target
.PHONY: all
all: $(SUBDIRS)

.PHONY: test
test: $(addprefix test-,$(SUBDIRS))

.PHONY: $(SUBDIRS)
$(SUBDIRS):
	$(MAKE) -C $@

test-%:
	$(MAKE) -C $* test

.PHONY: clean
clean: $(addprefix clean-,$(SUBDIRS))

clean-%:
	$(MAKE) -C $* clean
