# List of subdirectories containing their own Makefiles
SUBDIRS ?= $(shell find . -mindepth 1 -maxdepth 1 -type d)

# Default target
.PHONY: all
all: $(SUBDIRS)

.PHONY: test
target: $(addprefix target-,$(SUBDIRS))

.PHONY: $(SUBDIRS) $(addprefix test-,$(SUBDIRS))
$(SUBDIRS):
	$(MAKE) -C $@

test-%:
	$(MAKE) -C $* test

# Clean target to clean all subdirectories
.PHONY: clean
clean: $(addprefix clean-,$(SUBDIRS))

clean-%:
	$(MAKE) -C $* clean

