all:
	$(MAKE) -C lib/gfx all
	$(MAKE) -C lib/gui all
	$(MAKE) -C flashboot all
	$(MAKE) -C flashmenu all

clean:
	$(MAKE) -C lib/gfx clean
	$(MAKE) -C lib/gui clean
	$(MAKE) -C flashboot clean
	$(MAKE) -C flashmenu clean
