THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(THIS_DIR)/Makefile.config

all: $(LIBRARY) $(PROGRAM)

$(PROGRAM): $(PROGRAM_PLAIN)
ifndef NO_EXOMIZER
	$(EXOMIZER) sfx basic $(EXOMIZER_FLAGS) -t 52 $(PROGRAM_PLAIN) -o $(PROGRAM)
else
	cp $(PROGRAM_PLAIN) $(PROGRAM)
endif

include $(THIS_DIR)/Makefile.build.$(TARGETCC)

test:
	@echo "No test to be done."
