all:
	$(MAKE) -C lib/ingle all
	$(MAKE) -C lib/ultimem all
	$(MAKE) -C lib/ultifs all
	$(MAKE) -C lib/gfx all
	$(MAKE) -C lib/gui all
	$(MAKE) -C flashboot all
#	$(MAKE) -C tgi-demo all
	$(MAKE) -C desktop all
	$(MAKE) -C vforth all
	$(MAKE) -C writenow all
	$(MAKE) -C brv-play all
	$(MAKE) -C installer all
#	$(MAKE) -C paint all

clean:
	$(MAKE) -C lib/ingle clean
	$(MAKE) -C lib/ultimem clean
	$(MAKE) -C lib/ultifs clean
	$(MAKE) -C lib/gfx clean
	$(MAKE) -C lib/gui clean
	$(MAKE) -C flashboot clean
#	$(MAKE) -C tgi-demo clean
	$(MAKE) -C desktop clean
	$(MAKE) -C vforth clean
	$(MAKE) -C writenow clean
	$(MAKE) -C brv-play clean
	$(MAKE) -C installer clean
#	$(MAKE) -C paint clean
