SRC := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TUNIX_LIB ?= $(SRC)/lib/

TARGET   ?= vic
TARGETCC ?= cc65

EXOMIZER ?= $(SRC)/contrib/exomizer-3.0.2/src/exomizer
EXOMIZER_FLAGS ?= -B -n

include $(SRC)/Makefile.config.$(TARGETCC)
