CC65_HOME = /usr/local
AS      = $(CC65_HOME)/bin/ca65
CC      = $(CC65_HOME)/bin/cl65
AR      = $(CC65_HOME)/bin/ar65
LD      = $(CC65_HOME)/bin/ld65
CFLAGS  = -t $(CC65_TARGET) --create-dep -O
LDFLAGS = -t $(CC65_TARGET) -m $(PROGRAM).map
