SRC := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TARGET    ?= vic
TARGETCC  ?= cc65
TUNIX_LIB ?= $(SRC)/lib/

PROGRAM_PLAIN  = $(PROGRAM).prg

EXOMIZER ?= $(SRC)/contrib/exomizer-3.0.2/src/exomizer
EXOMIZER_FLAGS ?= -B -n

include $(SRC)/Makefile.config.$(TARGETCC)
