name: Build and Test on Multiple Platforms

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up C Compiler
      run: sudo apt-get install -y gcc make

    - name: Install VICE Emulator
      run: sudo apt-get install -y vice

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: make allworlds

    - name: Run Tests
      run: make test
