name: Build and test on Ubuntu

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up prerequisites
      run: sudo apt-get install -y gcc make vice texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra pandoc zip

    - name: Create config file
      run: echo -e "TARGET=unix\n" > src/config

    - name: Build Unixoid
      run: make clean all GC_STRESS=1 VERBOSE_LOAD=1

    - name: Run Tests
      run: make test

    - name: Make PDF manual
      run: cd src/bin/lisp/doc && ./md2pdf.sh && cd -

    - name: Build all worlds
      run: make allworlds VERBOSE_LOAD=1

    - name: Create ZIP file
      run: |
        cp src/bin/lisp/doc/manual.pdf tunix-lisp.pdf
        cp src/bin/lisp/doc/manual.md tunix-lisp.md
        rm tunix-lisp.unix.d64
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        DATE=$(date +'%Y-%m-%d')
        ZIP_NAME="${BRANCH_NAME}-${DATE}.zip"
        zip -o tunix-lisp.cbm.d64-images.$ZIP_NAME *.d64

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: '*.zip'

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.1 # Set the tag name dynamically as needed
        release_name: Release v0.0.1 # Customize the release name as needed
        body: |
          TUNIX Lisp for the Commodore C128, C16, C64, Plus/4 and VIC-20.
        draft: false
        prerelease: false
        files: '*.zip'
