name: Build and test on Ubuntu

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: "github.head_ref == 'main' || github.head_ref == 'development'"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up prerequisites
      run: sudo apt-get install -y gcc make texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra pandoc zip gdb

    - name: Create config file
      run: echo -e "TARGET=unix\n" > src/config

    - name: Build host tools
      run: make host

    - name: Run tests
      run: make test

    - name: Test compile-time configurations
      run: ./scripts/test-unix.sh

    - name: Make PDF manual
      run: cd src/bin/lisp/doc && ./md2pdf.sh && cd -

    - name: Build all worlds
      run: make allworlds VERBOSE_LOAD=1
