name: Build and Test on Multiple Platforms

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C Compiler
      run: sudo apt-get install -y gcc make

    - name: Install cc65
      run: sudo apt-get install -y cc65

    - name: Install VICE Emulator
      run: sudo apt-get install -y vice

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: make allworlds

    - name: Run Tests
      run: make test

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Add MSYS2 to PATH
      run: echo "C:\\msys64\\mingw64\\bin" >> $env:GITHUB_PATH

    - name: Install cc65
      run: choco install cc65

    - name: Install VICE Emulator
      run: |
        choco install vice
        echo "::add-path::C:\\Program Files\\VICE"

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: mingw32-make allworlds

    - name: Run Tests
      run: mingw32-make test

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C Compiler
      run: brew install gcc make

    - name: Install cc65
      run: brew install cc65

    - name: Install VICE Emulator
      run: brew install vice

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: make allworlds

    - name: Run Tests
      run: make test

