name: Build and Test on Multiple Platforms

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Initialize submodules

    - name: Set up C Compiler
      run: sudo apt-get install -y gcc make

    - name: Install VICE Emulator
      run: sudo apt-get install -y vice

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: make allworlds

    - name: Run Tests
      run: make test

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Initialize submodules

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Add MSYS2 to PATH
      run: echo "C:\\msys64\\mingw64\\bin" >> $env:GITHUB_PATH

    - name: Download and Install VICE
      run: |
        Invoke-WebRequest -Uri https://sourceforge.net/projects/vice-emu/files/latest/download -OutFile vice.zip
        Expand-Archive -Path vice.zip -DestinationPath C:\Programs\VICE
        echo "C:\Programs\VICE" >> $env:GITHUB_PATH

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: mingw32-make allworlds

    - name: Run Tests
      run: mingw32-make test

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Initialize submodules

    - name: Set up C Compiler
      run: brew install gcc make

    - name: Install VICE Emulator
      run: brew install vice

    - name: Create config file
      run: echo -e "TARGET=vic20\nNDEBUG=1" > src/config

    - name: Build Project
      run: make allworlds

    - name: Run Tests
      run: make test

