name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Github environment
      id: setup_environment
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "ZIP_NAME=tunix.${{ env.VERSION }}+${{ env.SHORT_SHA }}.zip" >> $GITHUB_ENV

    - name: Install prerequisites
      run: sudo apt-get install -y gcc make texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra pandoc zip

    - name: Create config file
      run: echo -e "TARGET=vic20" > src/config

    - name: Build project
      run: make allworlds NDEBUG=1 VERBOSE_LOAD=1 TEST=1

    - name: Run tests
      run: make test

    - name: Test compile-time configurations
      run: ./test-unix.sh

    - name: Zip files
      run: ./make-bin-release.sh ${{ env.ZIP_NAME }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: TUNIX Lisp ${{ github.ref }}
        body: |
          TUNIX Lisp D64 images for the Commodore C128, C16, C64, Plus/4, and VIC-20, and manual in Markdown and PDF format.
        draft: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/test-release') }}
        prerelease: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/test-release') }}
        release: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/master') }}

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.ZIP_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
